### ISSUE TITLE
spi support for 16 bit

### ISSUE THREAD

**Issue by Vishnu-Mohan** [daniel-santos/mcp2210-linux#16]
HI all ,

 After successfully configuring the IC i am able to get spidev nodes and do communication also through spidev nodes. Now what i needed to know is this chip supports "16 bit spi word len or not ", from the driver side developer is throwing some error like  " mcp2210_spi_setup: MCP2210 only supports 8 bits per word, got request for 16 "  after checking the condition of bits_per_word , but i didn't find any thing related this on chip datasheet . so can some-body lead where this is specified in microchip forum / datasheet like it will support only 8 bit , or is it the driver limitation ?  please confirm .

**Comment by daniel-santos** [comment]
This issue comes up a lot, often in emails. The MCP2210 data sheet contains no information on commands to set the word size and there's nothing that a driver can do to alter or work-around that.

However, if your needed word size is a multiple of 8 and you either don't have a delay between words requirement or you do but the device can tollerate a delay in the middle of the word as well, then you should be fine with the MCP2210. Otherwise, you'll have to go with a better device like one of the the FTDI products (http://www.ftdichip.com/FT-X.htm). Unfortunately, I haven't written a driver for these yet, but the plan is to eventually make a generic library for USB-to-xxx bridge devices and then move both the MCP2210 driver and a new FTDI driver on top if that library.
